title = "Sauca Live Light"
baseURL = "https://www.saucalivelight.com/"
#baseURL = "/"
languageCode = "en-gb"
theme = 'ananke'
resourceDir = "/resources"
canonifyURLs = true

DefaultContentLanguage = "en"
SectionPagesMenu = ""
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "G-2RWEPSHDXC"
enableRobotsTXT = true
enableInlineShortcodes = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[languages]
  [languages.en]
   title = "Sauca Live Light"
   weight = 1
   contentDir = "content/en"
   # languageDirection = 'rtl' for Right-To-Left languages
#  [languages.fr]
#    title = "Ananke Fr"
#    weight = 2
#    contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Fraggle"
  favicon = "/images/favicon.png"
  site_logo = "/images/logoballtext.svg"
  description = "The next chapter in audience participation."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 0
  custom_css =  ["custom.css"]

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/profile.php?id=100086496160639"
label = "Sauca Facebook"
#color = '#3b5998'

[[params.ananke_socials]]
name = "linkedin"
url = "https://www.linkedin.com/company/sauca-limited/"
label = "LinkedIn"
#color = '#0a66c2'

[[params.ananke_socials]]
name = "YouTube"
url = "https://www.youtube.com/channel/UCnmk1PNswOvtVZP8-A_ObkA"
label = "YouTube"
color = '#ff0000'

[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/saucalivelight"
label = "Share on instagram"
color = '#c32aa3'


[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/"
label = "Share on Twitter"
color = '#1da1f2'
follow = false

[[params.ananke_socials]]
name = "linktree"
url = "https://linktr.ee/saucalivelight"
label = "Share on Twitter"
color = '#45E65F'
